name: win-build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["windows"]
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install Crystal
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
          scoop install crystal
      - name : Install dependencies
        run: |
          shards install --without-development --release
      - name : Build executable
        run: |
          shards build --release
      - uses: actions/upload-artifact@v3
        with:
          name: deepl-cli-${{ matrix.os }}
          path: bin/deepl
